version: "3.9"
services:
  postgres:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./database:/docker-entrypoint-initdb.d
  node:
    build: "./server"
    image: todolist:server
    ports:
      - 8080:8080
    command: node /app/server.js
    volumes:
      - server_node_modules:/app/node_modules
      - ./server:/app
    depends_on:
      - postgres
  angular:
    build: "./client"
    image: todolist:client
    working_dir: /app
    ports:
      - 4200:4200
    command: npm run start
    volumes:
      - client_node_modules:/app/node_modules
      - ./client:/app
    links:
      - node
volumes:
  server_node_modules:
  client_node_modules:
